// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPR6yXvlWZF2c9ftD3r6daP6-wV6Oi368',
    appId: '1:925464669445:web:c747792162a136891c5b6c',
    messagingSenderId: '925464669445',
    projectId: 'cipher-schools-assignment',
    authDomain: 'cipher-schools-assignment.firebaseapp.com',
    storageBucket: 'cipher-schools-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVAadavWbsRKC_z_xCCG0JSgRctkNjNbI',
    appId: '1:925464669445:android:a2ef68173b222bbd1c5b6c',
    messagingSenderId: '925464669445',
    projectId: 'cipher-schools-assignment',
    storageBucket: 'cipher-schools-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZhpeQI0V4meG2AKNtLsUSW2grGDbEw2c',
    appId: '1:925464669445:ios:d5936076c3c5c1b81c5b6c',
    messagingSenderId: '925464669445',
    projectId: 'cipher-schools-assignment',
    storageBucket: 'cipher-schools-assignment.appspot.com',
    iosBundleId: 'com.cipherschools.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZhpeQI0V4meG2AKNtLsUSW2grGDbEw2c',
    appId: '1:925464669445:ios:ede055490cc58f1f1c5b6c',
    messagingSenderId: '925464669445',
    projectId: 'cipher-schools-assignment',
    storageBucket: 'cipher-schools-assignment.appspot.com',
    iosBundleId: 'com.cipherschools.assignment.RunnerTests',
  );
}
